### ISSUE TITLE
Implement BiMPM

### ISSUE THREAD

**Issue by WelcomeLi** [NTMC-Community/MatchZoo#183]
The artical about the BiMPM (https://arxiv.org/abs/1702.03814) gives the performance(MAP) of BiMPM in WikiQA is 0.718 , but in MatchZoo we find that the BiMPM products slowly and only can get the performance(MAP) of 0.54. Can someone give me some reason? thanks!

**Comment by faneshion** [comment]
@rgtjf is working on this model. As I have known, this model have not been completely finished. More details ask @rgtjf.

**Comment by rgtjf** [comment]
This model is still in construction for the bad performance. I will try to find out bugs and fix them.

Also, the original repository (https://github.com/zhiguowang/BiMPM) implemented by tensorflow is for your reference.

> the BiMPM products slowly

Many time is spent on producing `Multi-perspective Matching`, and I am thinking an efficiency implementation.  Any idea is welcome.

**Comment by bwanglzu** [comment]
@rgtjf If we have the exact same implementation as the official repo, do you think we'll reach the same level of MAP (or other metrics)? I was wondering that the best model in our `models` folder (i.e. DRMM-TKS) only achieved 65%.

Besides, I guess the best thing to do is to  make it happen in Matchzoo 2.0 using the new `base_model`.

**Comment by rgtjf** [comment]
Sure,  since the backends are the same.

@bwanglzu It is amazing to see the changes of  `Matchzoo 2.0`. I will try the new `base_model`.

**Comment by bwanglzu** [comment]
@rgtjf let's wait until #169 merged into 2.0:)

**Comment by bwanglzu** [comment]
@rgtjf Are you still willing to work on this, or let me take over?

**Comment by bwanglzu** [comment]
@rgtjf can you take a look at #423 ?
