### ISSUE TITLE
what does `dpool_index` stands for in MatchPyramid?

### ISSUE THREAD

**Issue by sanshanxiashi** [NTMC-Community/MatchZoo#203]
我看MatchPyramid的输入有3个model = Model(inputs=[query, doc, dpool_index], outputs=out_),
query和doc是两个句子，那这里的dpool_index是啥意思呢？
大神帮我解答一下子。

There're three inputs in MatchPyramid: `query`, `doc` and `dpool_index`. The first two are sentences, but what does the `dpool_index` here means? Thanks in advance.

**Comment by bwanglzu** [comment]
if possible please use English to ask questions. It'e easier for others to answer & trace back.

**Comment by pl8787** [comment]
In order to implement dynamic pooling layer, we need pre-calculate the pooling index considering the two sentences length.

**Comment by bwanglzu** [comment]
@sanshanxiashi hope your question has been solved, I'll close this issue.

If you have further questions please feel free to create a new issue.

Best.

**Comment by voladorlu** [comment]
@bwanglzu  Hi, I got this error when running MatchPyramid with the standard model config suggested by tutorial. The input data can successfully work on several models like DSSM, ArcII. But it outputs this error when trying to run MatchPyramid. I'm not sure where goes wrong. Have ever met this issue?

ValueError: No data provided for "dpool_index". Need data for each key in: ['text_left', 'text_right', 'dpool_index']

**Comment by gouxute** [comment]
@bwanglzu  @voladorlu  i have got this error too.

**Comment by bwanglzu** [comment]
@voladorlu @gouxute This one works for you? https://github.com/NTMC-Community/MatchZoo/blob/master/tutorials/wikiqa/matchpyramid.ipynb

**Comment by voladorlu** [comment]
@bwanglzu  Thanks so much. I already found this few months ago. However, it's very strange that there exists a strange gap in both performance and efficiency when using different training loss e.g. MSE, HingeLoss, CrossEntropy. I exactly follow the tutorial notebook. When using pairwise loss, massive number of time will be spent on building training pairs. Moreover, the training loss also goes down pretty hard. Such issue is not a special case for MatchPyramid, also existing in DRMM, ARC-II etc. In contrast, MSE loss seems to work for different models. I'm not sure where goes wrong. It should not exist such issue if exactly following the tutorial notebook. Have you ever met such issue when using pairwise loss?

**Comment by faneshion** [comment]
Are you working on the ranking task or the classification task? The pairwise loss only fits for the ranking task. It indeed takes time to construct pairs if your data contains a number of positive documents for each query.
