### ISSUE TITLE
Add elasticsearch to the benchmark (NDCG and MAP)

### ISSUE THREAD

**Issue by denisb411** [NTMC-Community/MatchZoo#224]
I think that adding elasticsearch's (with default configuration) benchmark to the results table is a good point for comparasion reasons as a lot of people uses the framework and don't know how much better (or worse) are the deeplearning models performing.

**Comment by bwanglzu** [comment]
elastic is developed for IR purpose, while neural information retrieval (NEU-IR) is part of our objective (see readme). It's worth to discuss through.
