### ISSUE TITLE
How to use the layers Match or MatchTensor with the output of a BiLSTM with sequences=True

### ISSUE THREAD

**Issue by thiziri** [NTMC-Community/MatchZoo#256]
Hi,
I'm trying to develop a matching model that uses bi-LSTM layer with a Match (or MatchTensor) layer, I've got the following error:

>  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 474, in assert_input_compatibility
>     str(K.ndim(x)))
> ValueError: Input 0 is incompatible with layer conv1d_1: expected ndim=3, found ndim=4

Here is the pipeline model:

```
q_mat = q_lstm_layer(q_embed)
d_mat = d_lstm_layer(d_embed)
input_mat = Match(normalize=True)([q_mat, d_mat])
merged = Conv1D(self.config['filters'], self.config['kernel_size'], 
                               activation=self.config['conv_activation'])(input_mat)
```
Could you highlight how to uses the Match and MatchTensor layers and what's the main difference between them, please?
Best regards
@pl8787 @faneshion @bwanglzu @yangliuy

**Comment by thiziri** [comment]
Another question is:
The output shape of `Match` layer above gives:

> [layer]: Match  [shape]: [None, None, None, 1] 

What does it represent?

**Comment by pl8787** [comment]
`None` means the dimension need to be inferred by TensorFlow.

**Comment by thiziri** [comment]
Thanks for your response @pl8787 , But what I'm asking about, is:
The shape of this output is `[batch_size, ?, ?, 1]` that corresponds to `[None, None, None, 1]` what does each dimension represent? (those I replaced by `?`)
Thanks

**Comment by pl8787** [comment]
It is [batch_size, sentence1_length, sentence2_length, 1 (word-word similarity value)].

**Comment by thiziri** [comment]
Okay ! Great :+1: 
Thanks
