### ISSUE TITLE
MatchZoo models do not support text_length greater then 100 (mostly)

### ISSUE THREAD

**Issue by thiziri** [NTMC-Community/MatchZoo#264]
Hi,
I'm running different models on MZ, in addition to my own model (under development in MatchZoo), but I've noticed that when the dataset is pretty large (ex: current dataset has `vocab_size> 470000` words), the training is impossible with  `text2_maxlen>=300`, I'm getting the following warning for all the different models:

> W tensorflow/core/framework/allocator.cc:101] Allocation of 8611800000 exceeds 10% of system memory.
 
Then the job is killed.

Could you, please, explain the reason why MatchZoo is using all this amount of memory?
Could you please give me a way to optimize this?

Best regards

**Comment by bwanglzu** [comment]
I'm not familiar with the current version, but if you're developing a brand new model, maybe it's easier to inherit from the 2.0 `base_model`, take a look at [dssm](https://github.com/faneshion/MatchZoo/blob/2.0/matchzoo/models/dssm_model.py) in 2.0.

**Comment by bwanglzu** [comment]
Hi @thiziri tis is an critical issue in the current version of Matchzoo , basically there are some bugs in the current `generators`. These bugs might cause:
1. Memory issue.
2. Inconsistency issue.

And has been reported multiple times by users. It's a bit tricky to read the code and resolve the problem by us (the code is not quiet readable), but we'll try to deliver 2.0 asap, and make sure everything is correct & efficient.

**Comment by thiziri** [comment]
Okay, we are looking forward to having the 2.0 release. 
Thank you.

**Comment by bwanglzu** [comment]
Hi @thiziri take a look at [arc1 example](https://github.com/NTMC-Community/MatchZoo/blob/2.0/matchzoo/preprocessor/arci_preprocessor.py), this is how we do pre-processing using a `FixedLengthUnit`. 

After your input has been pre-processed, you can employ a generator (point-wise, pair wise or list wise) to generate batches of data, then feed into your created keras model.

An example 2.0 pipeline is illustrated at [here](https://nbviewer.jupyter.org/github/faneshion/MatchZoo/blob/2.0/notebooks/wikiqa/dssm.ipynb)
