### ISSUE TITLE
Implement MIX

### ISSUE THREAD

**Issue by SmileYuhao** [NTMC-Community/MatchZoo#287]
At KDD 2018, it published a new paper:  [**MIX**](http://www.kdd.org/kdd2018/accepted-papers/view/mix-multi-channel-information-crossing-for-text-matching). And the evaluation of this model seems pretty good.

I would like to know that, do you plan to implement this model as part of MatchZoo? 

Thanks :)

**Comment by bwanglzu** [comment]
@SmileYuhao Hi, I guess the best thing to do is to make it happen in MatchZoo 2.0, checkout to [2.0]() branch to have a look.

Currently we're focus on building existent models using 2.0 architecture, would you like to contribute? If so we can discuss in detail about this.

Best!

**Comment by bwanglzu** [comment]
@faneshion @pl8787 @yangliuy how do you think?

**Comment by faneshion** [comment]
@SmileYuhao are you one of the authors in the paper? Any suggestions and contribution are welcome!

**Comment by SmileYuhao** [comment]
@bwanglzu @faneshion Apologize for a delayed response. Unfortunately, I'm not one of authors. 

On the other hand, I will be very happy if I can do any contribution. 

Best :)

**Comment by bwanglzu** [comment]
@SmileYuhao nice.
@faneshion how do you think?

**Comment by faneshion** [comment]
That's nice. You can refer to [this file](https://github.com/faneshion/MatchZoo/blob/2.0/CONTRIBUTING.md) to know how to contribute.
