### ISSUE TITLE
In relation_train.txt composition

### ISSUE THREAD

**Issue by KoreaLee** [NTMC-Community/MatchZoo#333]
in relation_train.txt format.

`{label}\t{query}\t{document}`

What value should I use for label?
For example, clicks and non-clicks of (query, document) are not appropriate,
Can I use ctr as a relvance score instead of click, non-click label?
If you use ctr, what kind of processing is required?
I wonder how everyone uses the label.

**Comment by pl8787** [comment]
It depends on your task. If you use ctr as target, you treat it as a regression task, and L2 loss can be applied.

**Comment by KoreaLee** [comment]
Thanks for replying

I tried applying the MatchPyramid model using CTR as label,
It is likely that you will need to work on additional CTRs that are too small and biasd.
When my target uses CTR, what should I do with additional preprocessing?

**Comment by KoreaLee** [comment]
In that issue, [#](https://github.com/faneshion/MatchZoo/issues/127)
I saw a description of the label.
So, do you normally calculate the relevance of two documents to be placed in a label manually?

**Comment by uduse** [comment]
Closed due to inactivity.
