### ISSUE TITLE
Different trained model using python 2.7 and python 3.6

### ISSUE THREAD

**Issue by logicmd** [NTMC-Community/MatchZoo#368]
Hi there,
I trained two models using tensorflow 1.7.0 with python 2.7 and python 3.6 in aws deeplearning ami 8.0.

By using the same data, config, the two models trained for both 1000 iterations are significantly different. 

Model using python 2.7 loss is converged to 0.2 and precision is 93%
Model using python 3.5 loss is converged to 0.4 and precision is 82%

Do you guys has any recommendation?

**Comment by bwanglzu** [comment]
Hi @logicmd I guess there is a bug in the generator in MatchZoo 1.0, but I'm not quiet sure about that.
@faneshion Can you answer?

**Comment by uduse** [comment]
Closed due to inactivity.
