### ISSUE TITLE
Implement MCAN？

### ISSUE THREAD

**Issue by guotong1988** [NTMC-Community/MatchZoo#370]
Multi-Cast Attention Networks

**Comment by bwanglzu** [comment]
@guotong1988 Hi, thanks for your comment, I was wondering would you like to contribute?

**Comment by guotong1988** [comment]
I am trying to implement it in tensorflow.  In fact I am not sure my implementation is right so I wish I could find a keras version here. If I success to implement it in tensorflow, I will contribute.

**Comment by bwanglzu** [comment]
@guotong1988 matchzoo is built based on keras, when I'm free, I'll read the paper.

I've created an issue in our [paper list](https://github.com/NTSC-Community/awaresome-neural-models-for-semantic-match/issues/10), if you're motivated, I can tell you how to do it for MatchZoo.

**Comment by yangliuy** [comment]
@guotong1988 Welcome to make contributions to MatchZoo!

**Comment by uduse** [comment]
Closed due to inactivity.
