### ISSUE TITLE
How do I implement the 2.0 metrics into DSSM model?

### ISSUE THREAD

**Issue by JacobPolloreno** [NTMC-Community/MatchZoo#372]
I tried looking at old version of MatchZoo but found the implementations to be different(more Keras like with y_true and y_pred).

I'm using the DSSM model with rank hinge loss and want to get MAP and NDCG metrics running. I see that they're implemented but not sure how to integrate them into the new API.

Any hints? Thanks

Currently using old implementation instead.
```
for epoch in range(1, train_params['epochs'] + 1):
	history = model.fit_generator(pairgenerator_train,
			              steps_per_epoch=train_params['steps_per_epoch'],
			              epochs=1,
			              verbose=train_params['verbose'])
	                      
	res = {}
	res['MAP'] = 0.0
	res['NCDG@3'] = 0.0
	res['NCDG@5'] = 0.0
	num_valid = 0
	for i in range(len(listgenerator_val)):
	    input_data, y_true = listgenerator_val[i]
	    y_pred = model.predict(input_data,
			           batch_size=len(y_true),
			           verbose=0)
	    res['MAP'] += mean_average_precision(y_true, y_pred)
	    res['NCDG@3'] += ndcg(3)(y_true, y_pred)
	    res['NCDG@5'] += ndcg(5)(y_true, y_pred)
	    num_valid += 1

	listgenerator_val.reset()
	logger.info(f"Iter: {epoch}\t" +
		    '\t'.join([f"{k}={v / num_valid:.3f}" for k, v in res.items()]))
```

**Comment by bwanglzu** [comment]
Hi @JacobPolloreno yes they're implemented, but the integration test was not done at the moment. 

We have to refactor the code a little bit, this has been assigned in issue #312 .

**Comment by bwanglzu** [comment]
I wrote a tutorial at [here](https://github.com/faneshion/MatchZoo/blob/hotfix/base-model/notebooks/wikiqa/dssm.ipynb), but we need to refactor the metrics a little bit.
