### ISSUE TITLE
is consistent process units' transformer IO type necessary?

### ISSUE THREAD

**Issue by ZizhenWang** [NTMC-Community/MatchZoo#394]
in process units' `transform` method, the input and output type are different like
- `list` input `list` output as `LowercaseUnit`
https://github.com/faneshion/MatchZoo/blob/b3d61fba9e7120a9216729f02cf8b9127208682d/matchzoo/preprocessor/process_units.py#L55
-  `list` input `np.ndarry` output as `WordHashingUnit`
https://github.com/faneshion/MatchZoo/blob/b3d61fba9e7120a9216729f02cf8b9127208682d/matchzoo/preprocessor/process_units.py#L329-L332
- `np.ndarry` input `np.ndarry` output as `SlidingWindowUnit`
https://github.com/faneshion/MatchZoo/blob/b3d61fba9e7120a9216729f02cf8b9127208682d/matchzoo/preprocessor/process_units.py#L374
even transform one type to another is easy, but is it necessary to require a consistent IO type for these units?

**Comment by uduse** [comment]
I agree that `list` and `np.ndarray` should be consistent.

**Comment by uduse** [comment]
Thanks for reporting. I fixed this by changing all of them to `list`.
