### ISSUE TITLE
[hotfix] cdssm preprocess dont need SlidingWindowUnit

### ISSUE THREAD

**Issue by ZizhenWang** [NTMC-Community/MatchZoo#420]
the first layer of CDSSM model is `Conv1D`, which doesn't need a extra `sliding window process` :dizzy_face:

**Comment by bwanglzu** [comment]
convince me it's a bug @ZizhenWang

**Comment by ZizhenWang** [comment]
assume input text is 
`[word1, word2, word3, word4, ... ]`
after word hashing ,it can be transformed to 
`[word1_ngram, word2_ngram, word3_ngram, word4_ngram, ...]`
the CDSSM file define the model structure as `Input -> Conv1D -> ...`
so if the input data has shape as `[word1_ngram, word2_ngram, word3_ngram, word4_ngram, ...]`,  `Conv1D` use the `kernel_size` to represent `sliding window length`, and convolute on the window contexts naturally, the inner compute formula can be `W * [word1_ngram, word2_ngram, word3_ngram] + b`, which is **right**
but with `sliding window unit`, the preprocessor output data like 
`[ [word1_ngram, word2_ngram, word3_ngram], [word2_ngram, word3_ngram, word4_ngram], ...]`
input these data to `Conv1D` layer, the inner compute is 
 `W * [[word1_ngram, word2_ngram, word3_ngram], [word2_ngram, word3_ngram, word4_ngram], [word3_ngram, word4_ngram, word5_ngram],] + b`, which is **wrong**

**Comment by bwanglzu** [comment]
no, the shape of the input data should be num_word_ngrams * 3dim_triletter.
After sliding window, the sentence "this is a test sentence" -> `[[this is a], [is a test], [a test sentence]]`
Each word, say it's a 30000 dimensional vector, then the sentence will be represented as:
```python
[0...1...1...0] # this is a 90000 d vector of `this is a`
[0...0...1...0] # 90000d of `is a test`
[1...0...1...0] # 90000d of `a test sentence`
```
So the input shape (x) should be num_word_ngrams (i.e. 3 here) * 90000.
Without sliding word unit, you didn't even have `word_ngram`, you only got `letter_ngram`, which is 30000d.

Letter-trigram -> `test` -> 30000d
Word-trigram -> `a test sentence` -> 90000d.

**Comment by ZizhenWang** [comment]
we should consider the convolution process, if the input data is `[[this is a], [is a test], [a test sentence]]` and the kernel size is 3, then the output is `W * [[this is a], [is a test], [a test sentence]] + b`, not what we wanted like `[[W * [this is a] + b], [W * [is a test] + b], [W * [a test sentence] + b]] `
