### ISSUE TITLE
[hotfix] redefine the 'stage'

### ISSUE THREAD

**Issue by faneshion** [NTMC-Community/MatchZoo#428]
The `stage` we have defined in `base_generator` and `base_preprocessor` should be redefined. It should contain '[train, test, predict]', where both 'train' and 'test' need to provide 'x' and 'y' as inputs, and 'predict' only need the 'x' as input.

**Comment by bwanglzu** [comment]
`train`, `dev` and `test` or `train`, `validation` and `test`? See [here](https://cs230-stanford.github.io/train-dev-test-split.html)
