### ISSUE TITLE
Add dssm noteboook for classification

### ISSUE THREAD

**Issue by faneshion** [NTMC-Community/MatchZoo#440]
The dataset for classification task is the quoraqp dataset (i.e., https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs). The whole process should include both `train`, `evaluate`, and `predict`.

**Comment by DuyguA** [comment]
Hello,
I looked for the link of the notebook. Would it be possible to share it?

**Comment by uduse** [comment]
@DuyguA the notebook is still under construction, an old version is available in 2.0 branch under the "notebook" dir.

**Comment by DaoD** [comment]
@uduse hi there, I find the PointGenerator (data generator) is removed in the version 2.0. But it is useful for the classification task. I find the PairGenerator is not good for training a classification model.

**Comment by uduse** [comment]
@DaoD `DataGenerator` is what you need.

**Comment by DaoD** [comment]
@uduse ok, thanks. Im using DynamicDataGenerator and set the func as lambda x: x.   XDDDDD
