### ISSUE TITLE
MatchSRNN Confusion

### ISSUE THREAD

**Issue by tc-yue** [NTMC-Community/MatchZoo#450]
在matchsrnn中
`match_tensor_permute = Permute((2, 3, 1))(match_tensor)`
这一层在后面没有用到吧。
还有matchsrnn的速度是不是很慢啊。

**Comment by bwanglzu** [comment]
hi @tc-yue thanks for your message. I'm not quiet sure about that, guess @faneshion will answer the question for you.
Besides, we're working on matchzoo 2.0 at the moment, checkout to 2.0 branch and take a look!  Efficiency issue will be taken into consideration.

Best!

**Comment by uduse** [comment]
Closed due to inactivity.
