### ISSUE TITLE
Hoempage suggestion

### ISSUE THREAD

**Issue by wqh17101** [NTMC-Community/MatchZoo#458]
Add some comments for the homepage 2.0

**Comment by uduse** [comment]
- I don't like this blue bar, but it's up to taste.
![image](https://user-images.githubusercontent.com/4717005/47636111-3377d680-db92-11e8-96ab-671261f79a66.png)
- Distorted logo
- The animation gif 
    - distorted
    - I checked its size and it is larger than 1M, which takes a while to load and also mobile unfriendly
    - too slow, speed it up at least 3x
- "Deep learning for semantic matching" -> "Deep Learning for Semantic Matching"

Also, is the page about "Deep Learning for Semantic Matching", the "NTMC-Community", or MatchZoo itself? I suggest using the whole thing to advertise matchzoo. e.g. title from "Deep learning for semantic matching" -> "MatchZoo"

**Comment by uduse** [comment]
Closed due to inactivity.
