### ISSUE TITLE
Parameter problem？

### ISSUE THREAD

**Issue by ZhikuoChen** [NTMC-Community/MatchZoo#474]
Hello! I have 2 problems.
1. https://github.com/NTMC-Community/MatchZoo/blob/master/examples/wikiqa/config/drmm_wikiqa.config
I think "embed_path": "./data/WikiQA/embed.idf" has a problem because the ‘"embed_size" is 300, and the dimension of embed.idf is one-dimensional.
2. What does the embed.idf file do?
Thank you!  I‘m looking forward to your reply.

**Comment by faneshion** [comment]
In the original DRMM paper, the term gating network used the idf as input. Here, we treat idf value of each term as a 1-dimension vector representation.

**Comment by ZhikuoChen** [comment]
OK. Then why does embed_size equal to 300 in https://github.com/NTMC-Community/MatchZoo/blob/master/examples/wikiqa/config/drmm_wikiqa.config?

**Comment by faneshion** [comment]
Sorry for the misleading information in the config file. Actually, In the WikiQA dataset, I have tested both 1-dimension idf and 300-dimension glove embedding in the term gating network. To be lazy, I have just renamed the glove embedding file as 'embed.idf'. I will fix this soon.

**Comment by ZhikuoChen** [comment]
Thank you very much for your answer!

**Comment by ZhikuoChen** [comment]
Thank you very much for your answer!
