### ISSUE TITLE
2.0-dev branch: why does mz.pack drop the label column?

### ISSUE THREAD

**Issue by cmacdonald** [NTMC-Community/MatchZoo#476]
Due to #273, we tried the 2.0 branch.
Due to #444, we are trying out the 2.0-dev branch, as 2.0 is not working.

In 2.0-dev, only sandbox.ipynb is still valid. 
I'm mystified about this line:
`train_pack.relation['label'] = np.random.randint(low=0, high=2, size=len(train_pack.relation))`
Why can't mz.pack retain any label that is present?

**Comment by uduse** [comment]
I'm sorry about your confusion, the `sandbox.ipynb` has the minimum explanation and 2.0-dev is still under active development. This random int assignment was not intended to initialize `label`. The original labels in the `train_pack` should work but we had a little problem debugging metrics, so I tried some random value to check if metrics are behaving correctly.

**Comment by cmacdonald** [comment]
Yes, your are right in that mz.pack doesnt affect the label, thanks!
