### ISSUE TITLE
Using MRR (Mean Reciprocal Rank) as a metrics on WikiQA datatset

### ISSUE THREAD

**Issue by nipunsadvilkar** [NTMC-Community/MatchZoo#484]
First of all, Thanks for such a great repo. It's like a goldmine for people interested in deep text matching.

I'm interested in doing an experiment on WikiQA with MRR as an evaluation metrics. Can anyone guide me to illustrate how to use MRR for wikiQA dataset instead of MAP. 

Though #306 provides this metric. I'm not able to integrate it with DRMM model.

Please help out. Thanks!

**Comment by bwanglzu** [comment]
Hi @nipunsadvilkar , our MatchZoo 2.0 is still under development,  [this](https://github.com/NTMC-Community/MatchZoo/blob/2.0-dev/sandbox.ipynb) page demonstrate the new API design, and it the MRR is implemented [here](https://github.com/NTMC-Community/MatchZoo/blob/2.0-dev/matchzoo/metrics/mean_reciprocal_rank.py).

We're still working to ship these features, it will be available in the coming month.

**Comment by uduse** [comment]
Closed due to inactivity.
