### ISSUE TITLE
setting embed file value in config file

### ISSUE THREAD

**Issue by shaheenkdr** [NTMC-Community/MatchZoo#498]
In the config file for wikiqa, it's set `"embed_size": 300` , As per the documentation, it says  "embed_size": word embedding size.  Can you please elaborate what exactly this value is ?

**Comment by faneshion** [comment]
As the model uses [word embeddings](https://en.wikipedia.org/wiki/Word_embedding) as inputs. The `embed_size` denotes the dimension of each word vector.

**Comment by shaheenkdr** [comment]
@faneshion Does this vary with respect to different datasets, if so how do I find the `embed_size` for my specific data set?

**Comment by faneshion** [comment]
The `embed_size` is a hyper-parameter, which likes the other hyper-parameters (e.g., the number of layers, the hidden size in each layer, etc.). The only way to find the best value is to experiment enough times to check the performance. Basically, you can try the values in `[50, 100, 300, 500, 1000]`, depending on the size of your training dataset.

**Comment by shaheenkdr** [comment]
@faneshion Thanks, apart from that what all other hyper-parameters can I optimise which could possibly improve the results substantially over a larger dataset ?
