### ISSUE TITLE
How to optimize hyper-parameters? 

### ISSUE THREAD

**Issue by shaheenkdr** [NTMC-Community/MatchZoo#502]
If the dataset size grows considerably, say if I were to rank for a larger dataset, with a `200,000` `vocab_size` , how should I approach to optimise the hyper parameters? For `Match Pyramid` as well as for `DRMM_TKS` , would the default `iteration=400`, `learning_rate=1.0` and default `adadelta` optimiser suffice to provide a solid result?  Thoughts on this ?

**Comment by uduse** [comment]
We have auto hyper-parameter tuning in 2.0, which will be released this month. Stay tuned (pun intended).
