### ISSUE TITLE
How much training data is required for a good model?

### ISSUE THREAD

**Issue by gtsoukas** [NTMC-Community/MatchZoo#507]
What is the required minimum number of unique *left texts* to train a good model?

Should each unique *left text* occur only once in the training samples or can it occur multiple times as *text left*?

I am generally struggling to produce a good model i.e. one with a high NDCG@k. I was following the [sandbox](https://github.com/NTMC-Community/MatchZoo/blob/2.0-dev/sandbox.ipynb) tutorial and filled the training data with 20% positive examples and 80% negative examples I used approx 2.5M samples in total. Resulting validation NDCG@5 is only approx 25% when trained with DSSM. It would be great to have a list of thinks to check in order to increase model quality.

**Comment by faneshion** [comment]
For your first question, there is no standard number of instances to train a good model. Many factors could impact the performance of a model. You can tune the parameters as much as possible, to find out the better model. For the second question, both `left` and `right` are the indexes from the `id` to `feature/text`, thus, it should occur only once. In the `relation`, they can appear multiple times as they need.
