### ISSUE TITLE
How to get word embedding vector from saved weights?

### ISSUE THREAD

**Issue by KoreaLee** [NTMC-Community/MatchZoo#555]
I think this question is related in https://github.com/NTMC-Community/MatchZoo/issues/101
when I use pre-trained embed in training. 
How to get word embedding vector from saved weights?
I want to check difference between pre-trained word embedding (glove) and trained embedding vector and then evaluate embedding vectors using tensorboard.

**Comment by faneshion** [comment]
As MatchZoo use keras as backend. The word embedding is also the weight matrix in the word embedding layer. Thus, you can directly dump the weight matrix of the embedding layer. As for how to dump, you can refer to [this page](https://github.com/keras-team/keras/issues/91).

**Comment by DaoD** [comment]
so the weight matrix is not accessible in the version 2.0?
