### ISSUE TITLE
fstring not supported in python 3.5

### ISSUE THREAD

**Issue by DaoD** [NTMC-Community/MatchZoo#573]
### Describe the bug
Traceback (most recent call last):
  File "/MRSwithOutline/MatchZooModels.py", line 2, in <module>
    import matchzoo as mz
  File "/py3.5/lib/python3.5/site-packages/MatchZoo-2.0.0-py3.5.egg/matchzoo/__init__.py", line 18, in <module>
    from .data_pack import DataPack
  File "/py3.5/lib/python3.5/site-packages/MatchZoo-2.0.0-py3.5.egg/matchzoo/data_pack/__init__.py", line 1, in <module>
    from .data_pack import DataPack, load_data_pack
  File "/py3.5/lib/python3.5/site-packages/MatchZoo-2.0.0-py3.5.egg/matchzoo/data_pack/data_pack.py", line 230
    f"`inplace` parameter of {func} not documented.\n"

### To Reproduce
import matchzoo as mz
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '1'

predict_pack = mz.datasets.wiki_qa.load_data('test', task='ranking')
preprocessor = mz.preprocessors.DSSMPreprocessor()
predict_pack_processed = preprocessor.transform(predict_pack)
print(predict_pack_processed)

### Describe your attempts
seems like some typo in the code, plz check it

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS**: ubuntu 16.04 
 - **Hardware**: Tesla K80 GPU

MatchZoo version: 2.0

**Comment by uduse** [comment]
@DaoD Yes. 3.6+ only for now. https://github.com/NTMC-Community/MatchZoo/issues/566 thumbs up here if you really want to use it on 3.5.

**Comment by DaoD** [comment]
@uduse can u provide a tutorial for classification task? it's hard to understand how to use load_data function

**Comment by DaoD** [comment]
when apply the model in classification problem:
https://github.com/NTMC-Community/MatchZoo/blob/master/matchzoo/data_generator/pair_data_generator.py#L90
when one text_left has only one sample, then the number of labels is 1. Thus the pair is []. Then the new_relation cause an error.

**Comment by uduse** [comment]
@DaoD We are working on classification tutorials and they will be released in 2 weeks. `load_data` of classification task is tricky since it returns a tuple of `(data_pack, classes)`. In terms of the pair generator, @faneshion .

**Comment by DaoD** [comment]
@uduse it's really confusing. 
If I use one_hot_encode_label, then the label would be in onehot format, and the function DPoolPairDataGenerator can not be used because there is a sort function in it.
If I do not use one_hot_encode_label, the model can not be used because the final dense layer is set as 2.

**Comment by uduse** [comment]
@pl8787
