### ISSUE TITLE
improve  homepage

### ISSUE THREAD

**Issue by wqh17101** [NTMC-Community/MatchZoo#574]
We need a Preview page  to show to introduce our package
a Team page to show our team
a Coming Soon page to show something we will do in the future
some community links to the media or group such as Weibo wechat group ，facebook ，zhihu and so on
maybe a sponsoring link to QRcode for wechat, AliPay, or paypal and so on

**Comment by faneshion** [comment]
Team page is no neccessary as the team information are listed in the `Readme.MD`.
