### ISSUE TITLE
How to pretrain a model and fine tune it?

### ISSUE THREAD

**Issue by DaoD** [NTMC-Community/MatchZoo#581]
### Describe the Question
How to pretrain a model and fine tune it?
I have pretrained a model on a pretrain dataset and I want to fine tune it on the other dataset. However, the data are different and the vocabulary dictionary is also different. So I need to change the input_shape in the fine tune model. But all the other parameters can be loaded from the pretrain model. How do I achieve this?
I find model.get_weights() and model.set_weights() are not available for the matchzoo model.

the matchzoo version is 2.0.

**Comment by ZizhenWang** [comment]
I think to fine-tune a pre-trained model, keep the vocabulary and input shape (e.g. text length) same is necessary, you can use MatchZoo's pre-processor to make them consistent. MatchZoo save models as Keras format, so you can use Keras' utils to process saved model, means `get/set_weights` is feasible.

**Comment by DaoD** [comment]
@ZizhenWang I don't use the same vocabulary in the fine tune stage. I only need to restore all paramaters except the embeddings. But I find it is hard to implement. 
Besides, I have already tried get_weights and set_weights function, and it reports that these two methods are not implemented in the Matchzoo model.

**Comment by uduse** [comment]
Yep. `model.backend` gives you the keras model.
