### ISSUE TITLE
CLSM implementation

### ISSUE THREAD

**Issue by sth4k** [NTMC-Community/MatchZoo#596]
Hi I have looked at the CDSSM model implementation, and i think it's different from the CLSM (which uses word-3-gram). Do you have implementation for CLSM? or is there no much big differences between the CDSSM and CLSM performance?

**Comment by bwanglzu** [comment]
there is some difference, but cdssm = clsm (Convolutional latent semantic model)
The current CDSSM uses word-hashing with 3 contextual windows.

**Comment by bwanglzu** [comment]
if you read the code, you'll find the difference is primary on the parameters, such as `relu` -> `tanh`, `sgd` -> `adaleta`, `dropout` -> no dropout in the original paper etc..

But all these parameters are tunable, you can just change the parameters, for example:

```python
model.params['dropout_rate'] = 0
```

to keep the model the same as the original implementation.

**Comment by sth4k** [comment]
Is the model.params['kernel_size'] doing the word-3-gram (also the 3 contextual windows you meantioned) in the CDSSM paper?

**Comment by sth4k** [comment]
Okay that clarifies my confusion. Thanks @bwanglzu and @ZizhenWang
