### ISSUE TITLE
DeepRank model

### ISSUE THREAD

**Issue by andrewyates** [NTMC-Community/MatchZoo#6]
Do you plan to release code for your DeepRank model (CIKM'17) as part of MatchZoo?

**Comment by pl8787** [comment]
Yes, it is in the schedule.

**Comment by bwanglzu** [comment]
Need some action on this issue.

**Comment by malarinv** [comment]
Found a textnet-model config for deeprank model here https://github.com/pl8787/textnet-model/blob/master/letor/config/letor.deeprank.2dgru.config couldn't find the corresponding implementation.. @pl8787 any suggestion on how to use it? Thanks.
