### ISSUE TITLE
About word_dict

### ISSUE THREAD

**Issue by dzhao123** [NTMC-Community/MatchZoo#602]
### Describe the Question
Hi there. I just want to know if the working pipeline will save a word dictionary file? Or the word dict is made on the fly.

### Describe your attempts
I read the document and code and it seems the word dict is made on the fly. Can I produce a word dict with matchzoo 2.0 and use it every time when I run the same data? By the way, is there a parameter to limit the word frequency of the word in word_dict.

**Comment by uduse** [comment]
Once you fit a preprocessor:
- `preprocessor.context['vocab_unit']` gives you the vocab unit
- `preprocessor.context['vocab_unit'].state['term_index']` gives you the term -> index mapping
- `preprocessor.context['vocab_unit'].state['index_term']` gives you the index -> term mapping

In terms of the frequency, a vocab can't directly filter word frequencies, instead, you may transform with `FrequencyFilterUnit` before transforming with a vocab unit. `BasicPreprocessor` has `filter_low_freq` and `filter_high_freq` for this behavior. For models can't use a basic preprocessor, you have to customize your own.

**Comment by dzhao123** [comment]
Thanks @uduse, oen more question. Is there a OOV design in matchoo 2.0? Is there a way to feed word embedding into model rather than input text into the model?

**Comment by uduse** [comment]
@dzhao123 Kinda. Please read the source of TermIndex and IndexTerm, see if those satisfy your needs. Models by default use texts, but as long as the input shapes and names match that of a processed data_pack.unpack(), it's fine.

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
