### ISSUE TITLE
DRMM model map score low on ROB04 collection

### ISSUE THREAD

**Issue by robertwt7** [NTMC-Community/MatchZoo#604]
Hi there

I'm doing research on information retrieval and am very interested with your work.

I tried to do a reranking task on the Robust04 collection with the default drmm config that i copied from wikiqa (tweaked the vocab size according to the embed.idf vocab count). I did 5 fold cross validation and got the map score of 0.2412166 which is lower than our bm25 score (0.255 after some parameter tuning). 

I believe that i did not choose the histogram method correctly. Where can i tune the histogram file to get the LCH mapping? Is there anything else i should know before getting the score on the paper?

I also tried to understand the gen_hist4drmm.py but i don't really get where to change the histogram mapping..  also, I did it on the Topic titles of Robust-04 collection if that makes any difference

Thanks!

**Comment by uduse** [comment]
I believe you're using matchzoo 1.0. It's no longer supported, but @faneshion might be able to help you. In 2.0, use histogram data generator and pass the mode. In 2.1, use data generator with a histogram callback that initialized with the mode.

**Comment by robertwt7** [comment]
Yes i'm using matchzoo 1.0 because i preprocessed all of the data previously using the 1st version and i haven't got a chance to play with the new version.. does the histogram data generator use LCH method by default in matchzoo 2?

Thanks for replying, appreciate it

**Comment by uduse** [comment]
2.0 is much more flexible than 1.0 so I highly suggest you to give it a try. No, it do not use LCH by default. However, the 2.0 tutorial of the model on wikiqa uses LCH so all you need to do is to understand how to load your data in 2.0, and just follow everything else on the tutorial.

**Comment by faneshion** [comment]
@robertwt7 Sorry for late responses as I am traveling these days. On Rob04 dataset, you need to deal with the data imbalance problem since the pairs for each query is significantly different (i.e., in the pair-wise case as is used in DRMM ), e.g., some query have thousands of pairs while some queries have tens of pairs. In this way, the model could be dominated by some specific query. Thus I have balanced the pairs for each query in the original [DRMM code](http://www.bigdatalab.ac.cn/benchmark/bm/bd?code=DRMM(LCH-IDF)). However, we have not implemented this sampling strategy in the MatchZoo to keep the consistency of the framework. This will be added in the next version of MatchZoo.

**Comment by robertwt7** [comment]
actually I was using queries and documents that was retrieved by BM25 so each of the queries has 1000 documents for 250 queries. There are however some documents that is not available in the qrels so i marked them as 0 (irrelevant). I was using LCH (by default) with IDF as well though. Currently re running with your setup of 30 nodes input histogram and 2 hidden layer of 5 node and 1 node respectively. Maybe I did not preprocess the data correctly? Is my setup correct for the data input?

Thanks for the reply though! Appreciate it

**Comment by robertwt7** [comment]
Thanks for the reply! Appreciate it.

No worries, i'll try to use negative sampling on the documents later... However when i'm referring to the paper, you said that you were using 30 hist size with 2 hidden layer of 5 and 1 node each respectively right? 

I'm currently trying to run based on the experiment setup on the paper and I'll try to get back with the map score after

**Comment by DQ0408** [comment]
Hi, I am intersted to your work too. This link http://www.bigdatalab.ac.cn/benchmark/bm/bd?code=DRMM(LCH-IDF)  couldn't download codes now, could you fix it? Appreciate for your help~
