### ISSUE TITLE
The data format of train,val,test for dssm

### ISSUE THREAD

**Issue by jifei** [NTMC-Community/MatchZoo#611]
Old version README.md mentioned Word Dictionary,Corpus File and Relation File. Now don‘t need them？
I want to use dssm to do Information Retrieval.Which files are needed，and what are about the data format of them. Where'is the example,just the same as the QA tutorials or still in the plan?

**Comment by uduse** [comment]
MatchZoo 2 does not create files for these purposes. Instead, MatchZoo 2 loads the data into a `DataPack` in memory, and go from there. Pleas read the documentation of `matchzoo.pack`, or follow [this](https://github.com/NTMC-Community/MatchZoo/blob/master/tutorials/data_handling.ipynb) tutorial for creating your own datapack.

**Comment by jifei** [comment]
> MatchZoo 2 does not create files for these purposes. Instead, MatchZoo 2 loads the data into a `DataPack` in memory, and go from there. Pleas read the documentation of `matchzoo.pack`, or follow [this](https://github.com/NTMC-Community/MatchZoo/blob/master/tutorials/data_handling.ipynb) tutorial for creating your own datapack.

I got it,ths!
