### ISSUE TITLE
Evaluation error in Matchpyramid tutorial

### ISSUE THREAD

**Issue by chenmengdx** [NTMC-Community/MatchZoo#615]
I'm trying to run the tutorial code of Matchpyramid, however, I encountered an error in the last step, when running:

model.evaluate(pred_x, pred_y, batch_size=5)

it says:

~/software/anaconda2/envs/matchzoo/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: indices[4,9,39] = [9, 5, 24] does not index into param shape [5,10,40,32]
	 [[{{node dynamic_pooling_layer_3/GatherNd}} = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2d_6/Relu, _arg_dpool_index_2_0_2)]]

Do you know why?

Thanks,
Meng

**Comment by uduse** [comment]
This is a known bug and @pl8787 is working on it. This occurs only when the `batch_size` is too small, and setting it to `len(pred_y)` is a workaround.

**Comment by pl8787** [comment]
It is already fixed now, please use the newest code.

**Comment by bwanglzu** [comment]
@pl8787 which pr?

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
