### ISSUE TITLE
No module in matchzoo

### ISSUE THREAD

**Issue by robertwt7** [NTMC-Community/MatchZoo#622]
I tried to install matchzoo 2 with pip and python setup.py straightaway

However when i tried to use it in jupyter notebook as the tutorial i can't seem to find any package in it

`AttributeError: module 'matchzoo' has no attribute 'datasets'`

I'm using the base environment in conda using pythong 3.6

Here's the location of my matchzoo:
`<module 'matchzoo' from '/home/sh1/S3713561/anaconda3/lib/python3.6/site-packages/MatchZoo-0.2.0-py3.6.egg/matchzoo/__init__.py'>`

I also tried to do `from matchzoo import datasets`. Does not seem to work with all of the other package such as **pack**,  **frame**, etc..

I just moved from MZ 1 to MZ 2 anyway. Tried to search on issues and docs and i can't find anything. Did anyone has the same issue here?

Also here's my server info:

> LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.5 (Maipo)
Release:	7.5
Codename:	Maipo

**Comment by bwanglzu** [comment]
@robertwt7 

1. ensure you installed matchzoo under python3 environment (pip3 install matchzoo if you have not set alias).
2. Ensure you're using the  python3 kernel of jupyter noteboook.

**Comment by uduse** [comment]
![image](https://user-images.githubusercontent.com/4717005/52718413-61b4e100-2fde-11e9-9c1c-4c2cc430d909.png)

Yep. Seems you have the old version. See the `0.2.0` there?

**Comment by robertwt7** [comment]
Oh yea I thought that was the naming convention. I don't know how do I got to matchzoo 0.2.0

Maybe it was the previous playground with mz 1. Re-installed, working like charm now. 

Thanks guys!
