### ISSUE TITLE
Vocab Unit does not provide correct number of Vocab size

### ISSUE THREAD

**Issue by robertwt7** [NTMC-Community/MatchZoo#629]
I'm running Rob04 collection with the WikiQA tutorial from DRMM model. 

Currently i'm stuck in loading the embedding matrix to my model where the **layer weight shape** is always short 1 then the **provided weight shape**.

Here's my current code and error:

```
glove_embedding = mz.datasets.embeddings.load_glove_embedding(dimension=300)
embedding_matrix = glove_embedding.build_matrix(preprocessor.context['vocab_unit'].state['term_index'])
In [10]:

# normalize the word embedding for fast histogram generating.
l2_norm = np.sqrt((embedding_matrix*embedding_matrix).sum(axis=1))
embedding_matrix = embedding_matrix / l2_norm[:, np.newaxis]
​
model.load_embedding_matrix(embedding_matrix)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-6b536ae92872> in <module>
      3 embedding_matrix = embedding_matrix / l2_norm[:, np.newaxis]
      4 
----> 5 model.load_embedding_matrix(embedding_matrix)

~/anaconda3/envs/TensorCPU/lib/python3.6/site-packages/matchzoo/engine/base_model.py in load_embedding_matrix(self, embedding_matrix, name)
    442         for layer in self._backend.layers:
    443             if layer.name == name:
--> 444                 layer.set_weights([embedding_matrix])
    445                 return
    446         raise ValueError(f"layer {name} not found. Initialize your embedding "

~/anaconda3/envs/TensorCPU/lib/python3.6/site-packages/keras/engine/base_layer.py in set_weights(self, weights)
   1055                                  str(pv.shape) +
   1056                                  ' not compatible with '
-> 1057                                  'provided weight shape ' + str(w.shape))
   1058             weight_value_tuples.append((p, w))
   1059         K.batch_set_value(weight_value_tuples)

ValueError: Layer weight shape (12289, 300) not compatible with provided weight shape (12290, 300)
```

When i was playing with Matchzoo1, I remember that i changed the vocab size according to the embed.idf that i got after i preprocess my robust data. Right now I believe that this is covered in 
`model.params['embedding_input_dim'] = preprocessor.context['vocab_size']` ?

However why do I get different weight shape? This example is only using first 1000 data from my Robust training data pack. Previously it took so long to generate full training data pack and I ended up with the same result (short 1)

Any help is really appreciated. Thanks

Edit:
I actually can overcome the issue by `model.params['embedding_input_dim'] = preprocessor.context['vocab_size'] + 1`

But why is the vocab size different than the number of vocab unit available in preprocessing class?

Thanks

**Comment by uduse** [comment]
possibly a #601 duplicate?

**Comment by robertwt7** [comment]
Oh yes! Sorry I tried to search from the issue but I didn't find it. It is indeed a duplicate.

Thanks for replying!
