### ISSUE TITLE
Why extra dense layer for CDSSM

### ISSUE THREAD

**Issue by sth4k** [NTMC-Community/MatchZoo#644]
I'm a bit confused of the CDSSM model structure. The second last layer is the dot product with normalization being True, so i suppose the score is between [0,1]. Can't we just use this score for ranking, why there is one more dense layer with linear activation after dot product?

I notice that, if i use the current model with dense layer as last layer, when i do model.predict, the order is 0, 1, 2. However if I use "model.backend.layers[-2]" (the dot product score), it will be in the order of 1,2,0.

**Comment by bwanglzu** [comment]
@sth4k you're correct, the original paper use cosine similarity to mearesure the similarity between query vector and document vector, the reason we add an extra dense layer is:

1. To keep model structure consistent.
2. To allow CDSSM working for ranking task as well as classification task.

**Comment by sth4k** [comment]
Yeah that's what i am thinking. Thanks for your reply!
