### ISSUE TITLE
How to add Chinese stopwords in model

### ISSUE THREAD

**Issue by yechens** [NTMC-Community/MatchZoo#656]
Hello, I want to consult how I can add Chinese stopwords in my model?
Thank you for your time!

**Comment by ZizhenWang** [comment]
https://github.com/NTMC-Community/MatchZoo/blob/1aad95b21e64a0e42d70c36317c77c8285a79a80/matchzoo/processor_units/processor_units.py#L100-L139
You can replace the func here. In `__init__` you need initial the stopwords, and define the filter method in `transform`

**Comment by uduse** [comment]
Inherit the `StopRemoval` class and overrides its property `stopwords` with your choice of words.
