### ISSUE TITLE
Parameters for preprocessing and model in DRRM v1?

### ISSUE THREAD

**Issue by datistiquo** [NTMC-Community/MatchZoo#683]
Some params in the model config files are related to preprocessing like hist_size. So changing them there leads to errors and you need to change the hist_size manually in eg.test_histogram_generator.py? That is a bit confusing or do I miss something?

I think this is just in v1 the case and the usage is enhanced in v2?

Very kind regards!

Edit:

In rank_io.py

```
def read_data(filename, word_dict = None):
    data = {}
    for line in open(filename):
        line = line.strip().split()
        tid = line[0]
        if word_dict is None:
            data[tid] = list(map(int, line[2:]))
        else:
            data[tid] = []
            for w in line[2:]:
                if w not in word_dict:
                    word_dict[w] = len(word_dict)
                data[tid].append(word_dict[w])
    print('[%s]\n\tData size: %s' % (filename, len(data)), end='\n')
    return data, word_dict
```

The sentence is only read from the second word due to line[2:] so the first word is missing.

**Comment by faneshion** [comment]
Hi @datistiquo , we ignored the first word as the line[1] denotes the length of the sentences. This the original version of the process code. Strongly recommend the latest version [V2.1](https://github.com/NTMC-Community/MatchZoo/releases/tag/v2.1)  which have introduced a number of new features.
