### ISSUE TITLE
Example training on GPU

### ISSUE THREAD

**Issue by jibrilfrej** [NTMC-Community/MatchZoo#686]
- [ ] I checked to make sure that this is not a duplicate issue
- [ ] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/NTMC-Community/awaresome-neural-models-for-semantic-match))

### Is your feature request related to a problem? Please describe.
I would like an example of code that train a model on GPU.
I did not manage to find any clear example or option on how to do that. Is it when declaring the model? when tuning it? when processing the data? 

### Describe the solution you'd like
In one of the notebook in the tutorials add a "train on GPU" section

### Additional Information
Other things you want the developers to know.

**Comment by uduse** [comment]
Training on GPU is not matchzoo's job but the job of it's underlying dependencies, i.e. keras. If you know how to train keras models on a GPU, then it's the same. If you don't then go ahead and find some tutorials on training keras models on GPU. If you want API in matchzoo that **better** supports training on GPU than native keras, then it's a different story.

**Comment by jibrilfrej** [comment]
ok, thank you
