### ISSUE TITLE
How to install version 2.1.0 only 2.0.0 founded

### ISSUE THREAD

**Issue by dingxianwang** [NTMC-Community/MatchZoo#689]
How to install version 2.1.0 through pip? How can I use version 2.1.0?

**Comment by uduse** [comment]
I believe 2.1.0 is not yet published on pip. You have to do a git pull then install it locally instead.

**Comment by faneshion** [comment]
@dingxianwang We have upload the 2.1.0 version into the pypi. You can try it with `pip install matchzoo`.
