### ISSUE TITLE
How to get the predicted documents?

### ISSUE THREAD

**Issue by datistiquo** [NTMC-Community/MatchZoo#706]
I use the DRRM model with RankCrossEntropyLoss. The output values model.predict() are also negative. What are their meanings? And how do I get the predicted document IDs for an input query? I would like to map this output to the corresponding documents. It seems a bit different to classification?

Thanks.

**Comment by datistiquo** [comment]
If I have the output like:

```
prediction
array([[ 2.1248043 ],
       [-0.7405751 ],
       [ 1.2434225 ],], dtype=float32)
```

Is the order of this array the same like from the input? So If I want to predict one query with 3 docs:

query    doc1
query    doc2
query    doc3

So the first precicted number 2.12 corresponds to doc1? For probabilieis I wouldtake the argmax but they are no probabilities?

**Comment by bwanglzu** [comment]
hi @datistiquo I'm not the person who designed this network, as far as I know, the final score (so called *matching score*) is produced by a *term gathering network*.

> erarchical matching patterns and produce a matching score. Finally, the overall matching score is generated by aggregating the scores from each query term with a term gating network computing the aggregation weights.

So this model  do not produce probability. 

[This](https://github.com/NTMC-Community/MatchZoo/blob/2547f9d1b302d0f166508ba39fa659dfa210a276/matchzoo/engine/base_model.py#L383) is the place we try to make prediction, you can see that it's simply an interface of keras `predict` method. You predictiono is made in sequence.

**Comment by bwanglzu** [comment]
@faneshion maybe you can elaberate a bit more on the result (negative valeus)?
