### ISSUE TITLE
sample code problem in README.md

### ISSUE THREAD

**Issue by yunhenk** [NTMC-Community/MatchZoo#707]
Something is wrong with the sample code in README.md.
### Pro 1
Line 112-113
```python
valid_x, valid_y = valid_processed.unpack()
evaluate = mz.callbacks.EvaluateAllMetrics(model, x=valid_x, y=valid_y, batch_size=len(pred_x))
```
The variable 'pred_x' doesn't exist in previous code, this makes the total sample code unable to run.
### Pro 2
nltk resource init
```
import nltk
nltk.download('stopwords')
nltk.download('punkt')
```
These code are also needed for the sample code to run.

**Comment by uduse** [comment]
The README is out-dated. Please see "tutorials/quick_start.ipynb" for a better reference.

@bwanglzu @faneshion I suggest removing the code in the README completely and replace it with our tutorial reference.

**Comment by yunhenk** [comment]
Got it, tutorial reference is better.

**Comment by bwanglzu** [comment]
Ill take over

**Comment by bwanglzu** [comment]
@uduse I personally perfer quick start in readme to give user a first impression on how it works.

**Comment by uduse** [comment]
@bwanglzu README shouldn't be too long, but I agree that a ~15 lines minimum working code would be nice.
