### ISSUE TITLE
Set default backend dl library.

### ISSUE THREAD

**Issue by voladorlu** [NTMC-Community/MatchZoo#713]
May I ask how to change the default backend dl engine.

I'm trying "import matchzoo as mz", it seems to using theano as the default backend.

I already have tensorflow and theano. But I wanna use tensorflow as default backend.

I checked the document, but didn't find the instructions.

**Comment by uduse** [comment]
This may be helpful https://keras.io/backend/

**Comment by voladorlu** [comment]
It looks helpful. Thank you so much!
