### ISSUE TITLE
model fit failure on certain batch sizes

### ISSUE THREAD

**Issue by uduse** [NTMC-Community/MatchZoo#715]
### Describe the bug
These four models fail to fit when setting batch_size to 4:
- DRMM
- MatchPyramid
- CDSSM
- DSSM

### To Reproduce
Set `batch_size` to 4 when running tests. See [this CI run](https://travis-ci.org/NTMC-Community/MatchZoo/jobs/515104537)

### Describe your attempts
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not a duplicate issue

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: macOS 10.14
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: CPU

**Comment by bwanglzu** [comment]
tried to set batch_size to 4 on ubuntu 18.04, can not reproduce the error (dssm & cdssm).

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
