### ISSUE TITLE
implement BPE preprocessor

### ISSUE THREAD

**Issue by ZizhenWang** [NTMC-Community/MatchZoo#717]
BPE is used many NLP tasks as machine translation, generation and pre-training, we will implement a BPE processor to support these requirements.

**Comment by bwanglzu** [comment]
but why do you think it's related to text matching?

**Comment by ZizhenWang** [comment]
It is basic tokenizer of Bert.

**Comment by bwanglzu** [comment]
if it's a tokenizer, then should be designed as a processor unit.

**Comment by sth4k** [comment]
I think it's more to solve the OOV (out-of-vocabulary) problem. Currently the vocabulary is only built from training data and thus maybe limited by how you choose your training data.
