### ISSUE TITLE
dssm's ndcg ,  map metrics are less than the matchzoo tutorials

### ISSUE THREAD

**Issue by Nicksphere** [NTMC-Community/MatchZoo#731]
I run the dssm algorithm with  matchzoo 2.0，found that the result of dssm's ndcg, map metrics are less than  matchzoo's  tutorials obviously. Is there a problem ？

### 
dataset : wiki 
environment:  python3.6

`my result: 
Validation: normalized_discounted_cumulative_gain@3(0.0): **0.18537827976306148** - normalized_discounted_cumulative_gain@5(0.0): **0.20825197021237893** - precision@1(0.0): 0.12164296998420221 - precision@3(0.0): 0.09268035808320169 - precision@4(0.0): 0.07780410742496051 - mean_reciprocal_rank(0.0): 0.19736153130702894 - mean_average_precision(0.0): **0.19227106490139664**
`

`
matchzoo tutorails result:  
Validation: normalized_discounted_cumulative_gain@3(0.0): 0.45663442312293695 - normalized_discounted_cumulative_gain@5(0.0): 0.5363645153841258 - mean_average_precision(0.0): 0.4956098197015037
`

**Comment by uduse** [comment]
You offer no clue, so I have no clue.

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
