### ISSUE TITLE
input_dpool_index for match_pyramid

### ISSUE THREAD

**Issue by Decalogue** [NTMC-Community/MatchZoo#743]
Hi!
How to build input_dpool_index for match_pyramid?
Thanks

inputs = [input_left, input_right, input_dpool_index]

**Comment by Decalogue** [comment]
Thank you so much!

**Comment by pl8787** [comment]
You can reference the code [dynamic_pooling.py](https://github.com/NTMC-Community/MatchZoo/blob/master/matchzoo/data_generator/callbacks/dynamic_pooling.py).

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.

**Comment by weibobo2015** [comment]
I have read the code dynamic_pooling.py, but i can not understand the meaning why we need to build the dpool index. Could you explain the meaning?

**Comment by pl8787** [comment]
@weibobo2015 You can find some explanations [here](https://github.com/pl8787/MatchPyramid-TensorFlow/issues/4).

**Comment by pl8787** [comment]
@weibobo2015 We also can use `tf.image.crop_and_resize` mentioned in #671 .

**Comment by weibobo2015** [comment]
> @weibobo2015 You can find some explanations [here](https://github.com/pl8787/MatchPyramid-TensorFlow/issues/4).

Thank you very much. So i think the purpose of this padding(or expanding?) is to keep the real info for pooling, otherwise, some real info will be discarded ? Am i right?

**Comment by weibobo2015** [comment]
@pl8787

**Comment by pl8787** [comment]
@weibobo2015  Yes

**Comment by weibobo2015** [comment]
@pl8787 Thank you！

**Comment by weibobo2015** [comment]
@pl8787 after i have read something about tf.image.crop_and_resize ROI pooling or ROI align, there is another question. Can i use this tf.image.crop_and_resize to export the dpool_size directly instead of exporting as [max_len_a, max_len_b] and doing dynamic pooling to dpool size?

**Comment by weibobo2015** [comment]
@pl8787 after i have read something about tf.image.crop_and_resize (ROI pooling or ROI align), there is another question. Can i use this tf.image.crop_and_resize to export the dpool_size directly instead of exporting as [max_len_a, max_len_b] and doing dynamic pooling to dpool size?

**Comment by pl8787** [comment]
@weibobo2015 Yes, you can use that function.

**Comment by weibobo2015** [comment]
@pl8787 👌，thank you. I'll have a try.

**Comment by weibobo2015** [comment]
@pl8787 after i test the function tf.image.crop_and_resize, i find that we need to resize to  [max_len_a, max_len_b] and do dynamic pooling. In addition, the sampling method in tf.image.crop_and_resize should be "nearest" rather than "bilinear" which is the default one. I think the reason is that the "nearest" sampling doesn't change the origin info,  just expand.
