### ISSUE TITLE
How to use fasttext (subwords) vectors in tensorflow embedding layer?

### ISSUE THREAD

**Issue by datistiquo** [NTMC-Community/MatchZoo#746]
Hey,

I just struggle to find out how can I use Fasttext wordvectors for OOV word (in general) in a keras/tensorflow embedding layer. There is nothing out there. Maybe someone has thought of that too and has some hints for me?

The way via word embedding look up works via indices like
tf.nn.embedding_lookup(word_embeddings, x1)

And you could have an index for one OOV. But how can I assign a specific vector (from a different and custom source like fasttext) at runtime?

I am not so experience with the inner working of tensorflow embedding_lookup.

Up to know I handle OOV words by splitting the OOV in known subwords! So I make more words out of a OOV.

**Comment by bwanglzu** [comment]
I have 0 experience with fasttest, maybe others can help.

**Comment by datistiquo** [comment]
@bwanglzu It has nothing to do with Fasttext! It is about manipulating/customisising word vectors by conditions! If you encounter an OOV word during prediction, how can you assign a specific vector to this this specific word (ie. you check the word for knwon subwords by your own method or using just fasttext...)

**Comment by bwanglzu** [comment]
@datistiquo take a look at `Vocabulary` class [here](https://github.com/NTMC-Community/MatchZoo/blob/2547f9d1b302d0f166508ba39fa659dfa210a276/matchzoo/preprocessors/units/vocabulary.py#L30).

btw, we're **volunteers** to maintain the **open source** project, you're not my customer.  Please ask your questioon in a modest way.

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
