### ISSUE TITLE
How to run tutorials? Where to download toy data?

### ISSUE THREAD

**Issue by ljch2018** [NTMC-Community/MatchZoo#747]
I cannot find any url or command to download the toy data ? Please show me how to download  them. Thank you very much.

**Comment by bwanglzu** [comment]
```python
import matchzoo as mz

ranking_task = mz.tasks.Ranking()

train_raw = mz.datasets.toy.load_data(stage='train', task=task)
test_raw = mz.datasets.toy.load_data(stage='test', task=task)
```

**Comment by napianlin** [comment]
How to run tutorials?  python3.6/site-packages/matchzoo/datasets/toy/train.csv' does not exist

**Comment by uduse** [comment]
Make sure you have the latest version of matchzoo installed (or pull it from the github), all the toy data should be included.

**Comment by seifer08ms** [comment]
It works in Python command line,  but not Jupyter notebook.

**Comment by uduse** [comment]
@seifer08ms make sure you set your notebook kernel correctly.

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
