### ISSUE TITLE
Which paper does the model ‘dense_baseline’ come from?

### ISSUE THREAD

**Issue by Ivan-Ji** [NTMC-Community/MatchZoo#750]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your MatchZoo version by running `import matchzoo; matchzoo.__version__`. If this gives you an error, then you're probably using `1.0`, and `1.0` is no longer supported. Then attach the corresponding label on the issue.

**Comment by uduse** [comment]
It's a stupid model without any deliberate design.

**Comment by Ivan-Ji** [comment]
And what about the model 'Naive'?

**Comment by Ivan-Ji** [comment]
> It's a stupid model without any deliberate design. I created its structure in 5 mins. Just use it to get things rolling.

And what about the model 'Naive'?

**Comment by Ivan-Ji** [comment]
And what about the model 'Naive'?

**Comment by bwanglzu** [comment]
@Ivan-Ji Same as `dense_baseline`.
