### ISSUE TITLE
Does MatchZoo work for Chinese dataset?

### ISSUE THREAD

**Issue by YuanEric88** [NTMC-Community/MatchZoo#754]
### Describe the Question
Do this framework work for Chinese data set and relevant task, like Chinese sentence semantic text similarity?

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your MatchZoo version by running `import matchzoo; matchzoo.__version__`. If this gives you an error, then you're probably using `1.0`, and `1.0` is no longer supported. Then attach the corresponding label on the issue.

**Comment by uduse** [comment]
#656 #163 #185

**Comment by uduse** [comment]
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.
