### ISSUE TITLE
How to get the evaluation index of each query

### ISSUE THREAD

**Issue by Ivan-Ji** [NTMC-Community/MatchZoo#760]
### Describe the Question
In the code, the final evaluation is only the overall evaluation, not the evaluation of each query. So how do I get the evaluations of each query in DSSM?

**Comment by Ivan-Ji** [comment]
Not the overall index of retrieval

**Comment by aszhanghuali** [comment]
您好，您说的这个问题您解决了嘛？ @Ivan-Ji

**Comment by Ivan-Ji** [comment]
> 您好，您说的这个问题您解决了嘛？ @Ivan-Ji

No

**Comment by matthew-z** [comment]
Unfortunately, `model.evaluate` does not provide such feature at this moment. However, once you get the ranked list for each query, it is quite simple to calculate the scores using other libraries or tools.
