### ISSUE TITLE
For text match problem, what is the different between question-question match and question-answer match?

### ISSUE THREAD

**Issue by guotong1988** [NTMC-Community/MatchZoo#773]
I know question-question match is a text similarity problem.
What about question-answer match or question-doc match? It is used in information retrieval.
question-question match is indeed text similarity. But how do you define question-answer similarity?
Thank you!!

**Comment by faneshion** [comment]
You can refer to the our paper "A Deep Look into Neural Ranking Models for
Information Retrieval" to get more discussion about different matching tasks.
