### ISSUE TITLE
how to use soft-labels on ranking task?

### ISSUE THREAD

**Issue by lis-kp** [NTMC-Community/MatchZoo#777]
hi, I wonder if it is possible to use probability values on the label columns when using dssm model for ranking. for example, instead of having something like [1,0,0,0,0], I would have [0.4, 0.1, 0.2, 0.25, 0.25 ]. 

thanks.

**Comment by faneshion** [comment]
Right now, we treat all labels as an integer, which is the case of usual ranking or classification task. Could you please tell us in which case you would use the float label?

**Comment by lis-kp** [comment]
using soft labels can lead to better model generalization, so I was wondering if it would be possible to use them in matchzoo.
