### ISSUE TITLE
 Could not read from TensorArray index 255 because it has not yet been written to

### ISSUE THREAD

**Issue by loveJasmine** [NTMC-Community/MatchZoo#78]
File "/home//.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home//.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home//.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: TensorArray spatial_gru_1/state_ta_1871@training/Adam/gradients: Could not read from TensorArray index 255 because it has not yet been written to.
         [[Node: training/Adam/gradients/spatial_gru_1/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayReadV3 = TensorArrayReadV3[_class=["loc:@spatial_gru_1/zeros"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](training/Adam/gradients/spatial_gru_1/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayGrad/TensorArrayGradV3, training/Adam/gradients/spatial_gru_1/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayReadV3/StackPop, training/Adam/gradients/spatial_gru_1/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayGrad/gradient_flow)]]

**Comment by faneshion** [comment]
Are you running Match-SRNN and produce this message?

**Comment by loveJasmine** [comment]
yes

**Comment by bwanglzu** [comment]
Need to figure out whether it's a bug.

**Comment by bwanglzu** [comment]
@faneshion any solutions?

**Comment by uduse** [comment]
Closed due to inactivity.
