### ISSUE TITLE
Tensorflow2.0目前是否全面支持？

### ISSUE THREAD

**Issue by hezhefly** [NTMC-Community/MatchZoo#789]
如题，我目前的运行环境使用是tf2.0版本，keras是为2.3.0。
但无法执行
报错信息如下：
```
~/anaconda3/lib/python3.7/site-packages/keras/engine/training.py in _prepare_total_loss(self, masks)
    690 
    691                     output_loss = loss_fn(
--> 692                         y_true, y_pred, sample_weight=sample_weight)
    693 
    694                 if len(self.outputs) > 1:

TypeError: __call__() got an unexpected keyword argument 'sample_weight'
```

**Comment by uduse** [comment]
matchzoo losses do not support `sample_weight`.

**Comment by hezhefly** [comment]
> matchzoo losses do not support `sample_weight`.

是啊，那目前为止是不支持keras2.3.0了，是吧？

**Comment by uduse** [comment]
这和 keras2.3.0 有什么关系吗？

**Comment by hezhefly** [comment]
> 这和 keras2.3.0 有什么关系吗？

keras升级到2.3.0会报错

**Comment by abelx** [comment]
same error
tensorflow==1.14.0
keras==2.3.0

**Comment by uduse** [comment]
@hezhefly @abelx Please provide a short snippet of code to reproduce the error, so I can investigate.

**Comment by bwanglzu** [comment]
I think this is an issue related to new version of keras & tensorflow, the best thing to do would be downgrade keras to a specified version, such as 2.2.4.

**Comment by bwanglzu** [comment]
@hezhefly May I know which loss function u're using? How can we reproduce the error?

**Comment by matthew-z** [comment]
Compile a model with `RankCrossEntropyloss`using keras 2.3, and you will get this error.

 keras 2.3 forced all the losses have `sample_weight` param: check
https://github.com/keras-team/keras/blob/1cf5218edb23e575a827ca4d849f1d52d21b4bb0/keras/engine/training.py#L692

or this commit

https://github.com/keras-team/keras/commit/910e1247b452f29c0297ec6e3bf52b28b24fefcf

**Comment by aszhanghuali** [comment]
@matthew-z The same question! 
AttributeError: module 'keras.backend' has no attribute 'tf'
Have you solved it?
Thank you, I look forward to your reply.

**Comment by matthew-z** [comment]
Please upgrade MatchZoo. The latest version has supported Keras 2.3

**Comment by aszhanghuali** [comment]
First of all, thank you for your reply! Secondly, my MatchZoo's version is 2.1.0




------------------ 原始邮件 ------------------
发件人: "Z ZH"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上8:14
收件人: "NTMC-Community/MatchZoo"<MatchZoo@noreply.github.com>;
抄送: "红楼小梦"<1319466165@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [NTMC-Community/MatchZoo] Tensorflow2.0目前是否全面支持？ (#789)



Please upgrade MatchZoo. The latest version has supported Keras 2.3

**Comment by matthew-z** [comment]
current version is 2.2.0

**Comment by hezhefly** [comment]
都放弃了，我把matchzoo从我的工程项目中单独抽离出来，打包在docker里运行了

**Comment by aszhanghuali** [comment]
Thank you for your reply.
Why can't I upgrade to 2.2.0, and the latest version is 2.1.0. Can you tell me how you operate?
Thank you again！


------------------ 原始邮件 ------------------
发件人: "Z ZH"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上8:25
收件人: "NTMC-Community/MatchZoo"<MatchZoo@noreply.github.com>;
抄送: "你一定会成为你想的那个人"<1319466165@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [NTMC-Community/MatchZoo] Tensorflow2.0目前是否全面支持？ (#789)




current version is 2.2.0

**Comment by bwanglzu** [comment]
Guess we forgot to upload to pypi after 2.3 realse..

**Comment by bwanglzu** [comment]
Sorry for the inconvenience.. I'll do it now.

**Comment by aszhanghuali** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you for doing it! I wanna to know what you are going to do.
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1319466165
                            
                    
                        
                            
                                    1319466165@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年10月24日 21:00，Wang Bo<notifications@github.com> 写道： 


Sorry for the inconvenience.. I'll do it now.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bwanglzu** [comment]
matchzoo 2.2 is on pypi, please:

```python
pip install matchzoo --upgrade
```
