### ISSUE TITLE
Question about Robust04 on DRMM

### ISSUE THREAD

**Issue by DQ0408** [NTMC-Community/MatchZoo#802]
Hi, I am intersted to your work too. This link http://www.bigdatalab.ac.cn/benchmark/bm/bd?code=DRMM(LCH-IDF) couldn't download codes now, could you fix it? I want to know how do you preprocess Robust04 dataset to reproduce DRMM's performance. Appreciate for your help~

**Comment by aszhanghuali** [comment]
the same question

**Comment by bwanglzu** [comment]
@faneshion can you answer?

**Comment by faneshion** [comment]
We have fixed the website.

**Comment by arian-askari** [comment]
The same problem.

**Comment by arian-askari** [comment]
Hi @DQ0408, by closing the issue you mean I should create new issue for this poblem? I apprecaite if it is possible for you to send the source code to me.
