### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by mb320** [NTMC-Community/MatchZoo#803]
I have got a couple of questions, first, is the size of vocab estimated automatically or I need to pass it some how? if that is the case, I can manually replace the dataset in toy with mine and everything should be ok?other thing is can I use a dataset for training and another one for testing lets say amazon for training and yahoo for test (without changin paramteres like vocab size myself). Second, is the array returned by the prediction function related to the ranking scores of corresponding queries? Thank you very much !

**Comment by bwanglzu** [comment]
1. see [quick start](https://github.com/NTMC-Community/MatchZoo/blob/master/tutorials/quick_start.ipynb):
![image](https://user-images.githubusercontent.com/9794489/70433947-42160a00-1a83-11ea-8c0e-9c4d988a66db.png)

2. why not? Same idea as transfer learning in cv as long as training/testing are the same language and in same domain (such as food review dataset).

3. I have no idea what you're asking.
