### ISSUE TITLE
"Unhashable type" error while preprocessing using BasicPreprocessor

### ISSUE THREAD

**Issue by kasramsh** [NTMC-Community/MatchZoo#805]
### Describe the Question
Hi! 
I am trying to use your awesome package for document-retrieval. Tried to run toy examples in tutorial to get my hands on but actually it didn't run as expected. 

Using BasicPreprocessor, I get a "TypeError: unhashable type: 'list'".
As seen in the attached images, right before using the preprocessor, my data looks exactly as shown in the tutorial. What could be the issue? my MZ version is 2.2.0

PS: I am using matchzoo on Amazon AWS SageMaker (conda_tensorflow_py36 kernel). Could it be a problem by any chance?

Thanks in advance and good luck with the great job!

- [x] I walked through the tutorials
- [x] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question

![prepare_data](https://user-images.githubusercontent.com/11387765/69532341-dc4f5b80-0f75-11ea-9e94-f606afc77ad5.png)
![data_looks_right](https://user-images.githubusercontent.com/11387765/69532340-dc4f5b80-0f75-11ea-8247-886c254baf63.png)
![error_raises](https://user-images.githubusercontent.com/11387765/69532339-dc4f5b80-0f75-11ea-988b-977c7f23a134.png)

**Comment by JZ95** [comment]
Hi guy, I think i got the same problem just like you... the Unhashbale list problem is not only limited to the BasicPreprocessor...

**Comment by Chriskuei** [comment]
https://github.com/NTMC-Community/MatchZoo-py/issues/106

**Comment by JZ95** [comment]
> [NTMC-Community/MatchZoo-py#106](https://github.com/NTMC-Community/MatchZoo-py/issues/106)

this works, cheers guy
