### ISSUE TITLE
The results of matchzoo

### ISSUE THREAD

**Issue by xuezzz** [NTMC-Community/MatchZoo#813]
Hi, I wonder the results of the tutorials/wikiqa/esim is the dev datas or the test datas, if it's dev data's result, how can I see the test data's result, and if test data's result , so on!  
Thanks!

**Comment by xuezzz** [comment]
oh! all the files of the wikiqa/

**Comment by bwanglzu** [comment]
checkout readme or tutorials.

You can add NDCG to your metrics:

```python
ranking_task.metrics = [
    mz.metrics.NormalizedDiscountedCumulativeGain(k=3),
    mz.metrics.MeanAveragePrecision()
]
```
