### ISSUE TITLE
How to properly call the DIIN model in the contrib file?

### ISSUE THREAD

**Issue by LymanBin** [NTMC-Community/MatchZoo#821]

**Comment by uduse** [comment]
Does this help? 

https://github.com/NTMC-Community/MatchZoo/blob/fe0ccdd82500d116a7f945539ed05566fce90434/matchzoo/contrib/models/diin.py#L17

**Comment by LymanBin** [comment]
I also refer to this, but when I run, I get an error：
 "ValueError: No data provided for" char_left ". Need data for each key in: ['text_left', 'text_right', 'char_left', 'char_right', 'match_left', 'match_right'] "
I was wondering if I did not call it properly except for these parameters. Is there a tutorial on the diin model?

**Comment by uduse** [comment]
I think you may need to preprocess your data with its designated preprocessor:

https://github.com/NTMC-Community/MatchZoo/blob/926466ce4bbb29812210ad84c77227456f113c6d/matchzoo/preprocessors/diin_preprocessor.py#L15-L55

**Comment by LymanBin** [comment]
alright, thank you very much
