### ISSUE TITLE
DRMM Model

### ISSUE THREAD

**Issue by Gautamshahi** [NTMC-Community/MatchZoo#823]
Hello,

There is confusion in running the model, I am trying to use DRMM model.

In the Tutorial folder, there is an implementation of DRMM model and in the model folder also there is a DRMM.py.

Is DRMM.ipynthe same as of DRMM.py?

How to run DRMM.py form models folder?

**Comment by uduse** [comment]
> In the Tutorial folder, there is an implementation of DRMM

Where is this "implementation" you are talking about?
