### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '\\site-packages\\matchzoo\\datasets\\toy\\train.csv'

### ISSUE THREAD

**Issue by saekomdalkom** [NTMC-Community/MatchZoo#833]
I'm trying to run tutorials/quick_start.ipynb
When I run this code:
```
train_raw = mz.datasets.toy.load_data(stage='train', task=task)
test_raw = mz.datasets.toy.load_data(stage='test', task=task)
```
This error is occuring:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
 in 
----> 1 train_raw = mz.datasets.toy.load_data(stage='train', task=task)
      2 test_raw = mz.datasets.toy.load_data(stage='test', task=task)

~\anaconda3\envs\ilovemeat\lib\site-packages\matchzoo\datasets\toy\__init__.py in load_data(stage, task, return_classes)
     42 
     43     path = Path(__file__).parent.joinpath(f'{stage}.csv')
---> 44     data_pack = matchzoo.pack(pd.read_csv(path, index_col=0))
     45 
     46     if isinstance(task, matchzoo.tasks.Ranking):

~\anaconda3\envs\ilovemeat\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    684     )
    685 
--> 686     return _read(filepath_or_buffer, kwds)
    687 
    688 

~\anaconda3\envs\ilovemeat\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    450 
    451     # Create the parser.
--> 452     parser = TextFileReader(fp_or_buf, **kwds)
    453 
    454     if chunksize or iterator:

~\anaconda3\envs\ilovemeat\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    934             self.options["has_index_names"] = kwds["has_index_names"]
    935 
--> 936         self._make_engine(self.engine)
    937 
    938     def close(self):

~\anaconda3\envs\ilovemeat\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1166     def _make_engine(self, engine="c"):
   1167         if engine == "c":
-> 1168             self._engine = CParserWrapper(self.f, **self.options)
   1169         else:
   1170             if engine == "python":

~\anaconda3\envs\ilovemeat\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1996         kwds["usecols"] = self.usecols
   1997 
-> 1998         self._reader = parsers.TextReader(src, **kwds)
   1999         self.unnamed_cols = self._reader.unnamed_cols
   2000 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\anaconda3\\envs\\ilovemeat\\lib\\site-packages\\matchzoo\\datasets\\toy\\train.csv'

(ilovemeat is my environment name)
I went to this path and I found there is no 'train.csv' in datsets/toy.
Should I put the data to this folder manually?

dependencies:
- matchzoo 2.2.0
- keras 2.3.1
- tensorflow 2.1.0

**Comment by saekomdalkom** [comment]
I copied and pasted data files manually and it seems it's working very well. 
I wonder why there was nothing in that path.

**Comment by faneshion** [comment]
This maybe that the python installation do not copy the data file into the destination path.
