### ISSUE TITLE
keras should be replaced by tf.keras

### ISSUE THREAD

**Issue by songzy12** [NTMC-Community/MatchZoo#844]
Reason:
https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/

Solution:
I will send a pull request later.

**Comment by uduse** [comment]
Hi, @songzy12 thank you for the contribution!

This project is no longer maintained, so I prefer to not touching the master branch and leave it "as is". That said, if you think this could be helpful for the others, I'm happy to accept it into a separate branch and have a notice in the `README.md` or something.

**Comment by songzy12** [comment]
Thanks Zeyi for the quick response!

Yes I am fine with this way. 

Just to mentione that the current requirements.txt would still introduce some incompitable dependencies. 
For example, we have `numpy >= 1.14` in [1], but somewhere in the code we would need `numpy ~= 1.19` (higher numpy version like 1.20 is incompitable) to work. 

We would also have fixed such issues with the target pull request.

[1] https://github.com/NTMC-Community/MatchZoo/blob/8a487ee5a574356fc91e4f48e219253dc11bcff2/requirements.txt#L5

**Comment by uduse** [comment]
@songzy12 I merged your changes into `2.3-dev`. I'm not sure about the future of the project, though. Maybe we shouldn't accept any more changes. @faneshion do you have any plan? Should we just archive the project?

**Comment by songzy12** [comment]
Thanks Zeyi!

A quick question: if this MatchZoo project is to be archived, do you have suggestions for alternatives that serving similar purposes? i.e., a compile of text matching models so that we can easily compare their performances and doing experiments.

I noticed there is a community "Hugging Face", but it seems they mainly focus on transformer and its variations.

**Comment by uduse** [comment]
@songzy12 Sorry, I personally don't work in the NLP field anymore so I'm not quite sure what's the best thing to use now. Transformer variants are strong and my understanding of the "Hugging Face" community is that it's much more engineering-oriented than the research community that MatchZoo resides in. They care more about scaling up an algorithm and less about fair comparison across different algorithms. What works in practice is what matters more there. This is unfortunate, as university-backed researchers usually don't have enough computation power and engineering skills to conduct research in that regard 😢

**Comment by songzy12** [comment]
@uduse Strongly agree on "This is unfortunate, as university-backed researchers usually don't have enough computation power and engineering skills to conduct research in that regard".

Thank you again for your kind reply and creating/maintaing such an excellent project so far.
